auth/urls.py
from django.conf.urls import patterns,url



urlpatterns = patterns('auth.views',
        
    #url(r'^$','authenticate.v_home'),
    
    url(r'^login/$','authenticate.v_login'),
    url(r'^logout/$','authenticate.v_logout'),
    url(r'^forgotPassword/$','authenticate.v_forgotPassword'),
    url(r'^resetPassword/$','authenticate.v_resetPassword'),
    
    url(r'^signup/$','user.v_add_user'),
    url(r'^setting/$','user.v_edit_user'),
    
    url(r'^validate$','authenticate.v_validate'),
    url(r'^recoverPassword$','authenticate.v_recoverPassword'),
    #url(r'^validate2/$','authenticate.v_validate2'),      
    #url(r'^test$','authenticate.v_test'),
)

newsletter/urls.py
from django.conf.urls import patterns

from surlex.dj import surl

from .views import (
    NewsletterListView, NewsletterDetailView,
    SubmissionArchiveIndexView, SubmissionArchiveDetailView,
    SubscribeRequestView, UnsubscribeRequestView, UpdateRequestView,
    ActionTemplateView, UpdateSubscriptionViev,
)

urlpatterns = patterns(
    '',

    # Newsletter list and detail view
    surl('^$', NewsletterListView.as_view(), name='newsletter_list'),
    surl(
        '^<newsletter_slug:s>/$',
        NewsletterDetailView.as_view(), name='newsletter_detail'
    ),

    # Action request views
    surl(
        '^<newsletter_slug:s>/subscribe/$',
        SubscribeRequestView.as_view(),
        name='newsletter_subscribe_request'
    ),
    surl(
        '^<newsletter_slug:s>/subscribe/confirm/$',
        SubscribeRequestView.as_view(confirm=True),
        name='newsletter_subscribe_confirm'
    ),
    surl(
        '^<newsletter_slug:s>/update/$',
        UpdateRequestView.as_view(),
        name='newsletter_update_request'
    ),
    surl(
        '^<newsletter_slug:s>/unsubscribe/$',
        UnsubscribeRequestView.as_view(),
        name='newsletter_unsubscribe_request'
    ),
    surl(
        '^<newsletter_slug:s>/unsubscribe/confirm/$',
        UnsubscribeRequestView.as_view(confirm=True),
        name='newsletter_unsubscribe_confirm'
    ),

    # Activation email sent view
    surl(
        '^<newsletter_slug:s>/<action=subscribe|update|unsubscribe>/'
        'email-sent/$',
        ActionTemplateView.as_view(
            template_name='newsletter/subscription_%(action)s_email_sent.html'
        ),
        name='newsletter_activation_email_sent'),

    # Action confirmation views
    surl(
        '^<newsletter_slug:s>/subscription/<email=[-_a-zA-Z0-9@\.\+~]+>/'
        '<action=subscribe|update|unsubscribe>/activate/<activation_code:s>/$',
        UpdateSubscriptionViev.as_view(), name='newsletter_update_activate'
    ),
    surl(
        '^<newsletter_slug:s>/subscription/<email=[-_a-zA-Z0-9@\.\+~]+>/'
        '<action=subscribe|update|unsubscribe>/activate/$',
        UpdateSubscriptionViev.as_view(), name='newsletter_update'
    ),

    # Action activation completed view
    surl(
        '^<newsletter_slug:s>/<action=subscribe|update|unsubscribe>/'
        'activation-completed/$',
        ActionTemplateView.as_view(
            template_name='newsletter/subscription_%(action)s_activated.html'
        ),
        name='newsletter_action_activated'),

    # Archive views
    surl(
        '^<newsletter_slug:s>/archive/<year:Y>/<month:m>/<day:d>/<slug:s>/$',
        SubmissionArchiveDetailView.as_view(), name='newsletter_archive_detail'
    ),
    surl(
        '^<newsletter_slug:s>/archive/$',
        SubmissionArchiveIndexView.as_view(), name='newsletter_archive'
    ),
)

newsletter/models.py
import logging
logger = logging.getLogger(__name__)

from django.db import models
from django.db.models import permalink

from django.template import Context, TemplateDoesNotExist
from django.template.loader import select_template

from django.utils.translation import ugettext_lazy as _
from django.utils.translation import ugettext
from django.utils.timezone import now

from django.core.mail import EmailMultiAlternatives

from django.contrib.sites.models import Site
from django.contrib.sites.managers import CurrentSiteManager

from django.conf import settings

from sorl.thumbnail import ImageField

from .utils import (
    make_activation_code, get_default_sites, ACTIONS, get_user_model
)
User = get_user_model()


class Newsletter(models.Model):
    site = models.ManyToManyField(Site, default=get_default_sites)

    title = models.CharField(
        max_length=200, verbose_name=_('newsletter title')
    )
    slug = models.SlugField(db_index=True, unique=True)

    email = models.EmailField(
        verbose_name=_('e-mail'), help_text=_('Sender e-mail')
    )
    sender = models.CharField(
        max_length=200, verbose_name=_('sender'), help_text=_('Sender name')
    )

    visible = models.BooleanField(
        default=True, verbose_name=_('visible'), db_index=True
    )

    send_html = models.BooleanField(
        default=True, verbose_name=_('send html'),
        help_text=_('Whether or not to send HTML versions of e-mails.')
    )

    objects = models.Manager()

    # Automatically filter the current site
    on_site = CurrentSiteManager()

    def get_templates(self, action):
        """
        Return a subject, text, HTML tuple with e-mail templates for
        a particular action. Returns a tuple with subject, text and e-mail
        template.
        """

        assert action in ACTIONS + ('message', ), 'Unknown action: %s' % action

        # Common substitutions for filenames
        tpl_subst = {
            'action': action,
            'newsletter': self.slug
        }

        # Common root path for all the templates
        tpl_root = 'newsletter/message/'

        subject_template = select_template([
            tpl_root + '%(newsletter)s/%(action)s_subject.txt' % tpl_subst,
            tpl_root + '%(action)s_subject.txt' % tpl_subst,
        ])

        text_template = select_template([
            tpl_root + '%(newsletter)s/%(action)s.txt' % tpl_subst,
            tpl_root + '%(action)s.txt' % tpl_subst,
        ])

        if self.send_html:
            html_template = select_template([
                tpl_root + '%(newsletter)s/%(action)s.html' % tpl_subst,
                tpl_root + '%(action)s.html' % tpl_subst,
            ])
        else:
            # HTML templates are not required
            html_template = None

        return (subject_template, text_template, html_template)

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name = _('newsletter')
        verbose_name_plural = _('newsletters')

    @permalink
    def get_absolute_url(self):
        return (
            'newsletter_detail', (),
            {'newsletter_slug': self.slug}
        )

    @permalink
    def subscribe_url(self):
        return (
            'newsletter_subscribe_request', (),
            {'newsletter_slug': self.slug}
        )

    @permalink
    def unsubscribe_url(self):
        return (
            'newsletter_unsubscribe_request', (),
            {'newsletter_slug': self.slug}
        )

    @permalink
    def update_url(self):
        return (
            'newsletter_update_request', (),
            {'newsletter_slug': self.slug}
        )

    @permalink
    def archive_url(self):
        return (
            'newsletter_archive', (),
            {'newsletter_slug': self.slug}
        )

    def get_sender(self):
        return u'%s <%s>' % (self.sender, self.email)

    def get_subscriptions(self):
        logger.debug(u'Looking up subscribers for %s', self)

        return Subscription.objects.filter(newsletter=self, subscribed=True)

    @classmethod
    def get_default_id(cls):
        try:
            objs = cls.objects.all()
            if objs.count() == 1:
                return objs[0].id
        except:
            pass
        return None


class Subscription(models.Model):
    user = models.ForeignKey(
        User, blank=True, null=True, verbose_name=_('user')
    )

    name_field = models.CharField(
        db_column='name', max_length=30, blank=True, null=True,
        verbose_name=_('name'), help_text=_('optional')
    )

    def get_name(self):
        if self.user:
            return self.user.get_full_name()
        return self.name_field

    def set_name(self, name):
        if not self.user:
            self.name_field = name
    name = property(get_name, set_name)

    email_field = models.EmailField(
        db_column='email', verbose_name=_('e-mail'), db_index=True,
        blank=True, null=True
    )

    def get_email(self):
        if self.user:
            return self.user.email
        return self.email_field

    def set_email(self, email):
        if not self.user:
            self.email_field = email
    email = property(get_email, set_email)

    def update(self, action):
        """
        Update subscription according to requested action:
        subscribe/unsubscribe/update/, then save the changes.
        """

        assert action in ('subscribe', 'update', 'unsubscribe')

        # If a new subscription or update, make sure it is subscribed
        # Else, unsubscribe
        if action == 'subscribe' or action == 'update':
            self.subscribed = True
        else:
            self.unsubscribed = True

        logger.debug(
            _(u'Updated subscription %(subscription)s to %(action)s.'),
            {
                'subscription': self,
                'action': action
            }
        )

        # This triggers the subscribe() and/or unsubscribe() methods, taking
        # care of stuff like maintaining the (un)subscribe date.
        self.save()

    def _subscribe(self):
        """
        Internal helper method for managing subscription state
        during subscription.
        """
        logger.debug(u'Subscribing subscription %s.', self)

        self.subscribe_date = now()
        self.subscribed = True
        self.unsubscribed = False

    def _unsubscribe(self):
        """
        Internal helper method for managing subscription state
        during unsubscription.
        """
        logger.debug(u'Unsubscribing subscription %s.', self)

        self.subscribed = False
        self.unsubscribed = True
        self.unsubscribe_date = now()

    def save(self, *args, **kwargs):
        """
        Perform some basic validation and state maintenance of Subscription.

        TODO: Move this code to a more suitable place (i.e. `clean()`) and
        cleanup the code. Refer to comment below and
        https://docs.djangoproject.com/en/dev/ref/models/instances/#django.db.models.Model.clean
        """
        assert self.user or self.email_field, \
            _('Neither an email nor a username is set. This asks for '
              'inconsistency!')
        assert ((self.user and not self.email_field) or
                (self.email_field and not self.user)), \
            _('If user is set, email must be null and vice versa.')

        # This is a lame way to find out if we have changed but using Django
        # API internals is bad practice. This is necessary to discriminate
        # from a state where we have never been subscribed but is mostly for
        # backward compatibility. It might be very useful to make this just
        # one attribute 'subscribe' later. In this case unsubscribed can be
        # replaced by a method property.

        if self.pk:
            assert(Subscription.objects.filter(pk=self.pk).count() == 1)

            subscription = Subscription.objects.get(pk=self.pk)
            old_subscribed = subscription.subscribed
            old_unsubscribed = subscription.unsubscribed

            # If we are subscribed now and we used not to be so, subscribe.
            # If we user to be unsubscribed but are not so anymore, subscribe.
            if ((self.subscribed and not old_subscribed) or
               (old_unsubscribed and not self.unsubscribed)):
                self._subscribe()

                assert not self.unsubscribed
                assert self.subscribed

            # If we are unsubcribed now and we used not to be so, unsubscribe.
            # If we used to be subscribed but are not subscribed anymore,
            # unsubscribe.
            elif ((self.unsubscribed and not old_unsubscribed) or
                  (old_subscribed and not self.subscribed)):
                self._unsubscribe()

                assert not self.subscribed
                assert self.unsubscribed
        else:
            if self.subscribed:
                self._subscribe()
            elif self.unsubscribed:
                self._unsubscribe()

        super(Subscription, self).save(*args, **kwargs)

    ip = models.IPAddressField(_("IP address"), blank=True, null=True)

    newsletter = models.ForeignKey('Newsletter', verbose_name=_('newsletter'))

    create_date = models.DateTimeField(editable=False, default=now)

    activation_code = models.CharField(
        verbose_name=_('activation code'), max_length=40,
        default=make_activation_code
    )

    subscribed = models.BooleanField(
        default=False, verbose_name=_('subscribed'), db_index=True
    )
    subscribe_date = models.DateTimeField(
        verbose_name=_("subscribe date"), null=True, blank=True
    )

    # This should be a pseudo-field, I reckon.
    unsubscribed = models.BooleanField(
        default=False, verbose_name=_('unsubscribed'), db_index=True
    )
    unsubscribe_date = models.DateTimeField(
        verbose_name=_("unsubscribe date"), null=True, blank=True
    )

templates/about.html
{% extends 'base_with_structure.html' %}


{% block content %}

	<h2>About Us</h2>
	<p style="line-height:2">MOOCs magazine is an initiative to upgrade masses about the latest updates and trends in the online education. This magazine will have sections specifying content related to different online courses and its benefits for uplifting future prospectus. Students interested in pursuing our online courses can read our informative blogs for staying connected. Our blog section will have useful content giving insight into different hemispheres of online education. We have updated our forum with a news section containing current updates in the online education industry. MOOCs magazine is a knowledge hub for aspirants who want to stay active about the changes erupting in the technological world of e-education. </p>

	<p style="line-height:2"> Let us understand MOOCs form a layman’s prospective. MOOCs is an innovative step towards spreading higher education globally to masses without any set barriers like availability, time etc. MOOCs has acquired a name which is  globally known, trusted and well appreciated by people who are already associated or willing to be associated. MOOC allows its students to have any time access via web to its massive range of courses. It provides a technically advanced approach towards obtaining knowledge and easy learning. It helps a student in having access to wide variety of online courses along with the privilege to study according to one’s own convenience. Almost all the higher courses of nearly every field are available with good quality study material in written as well as in interactive forms. Videos from renowned and eminent personalities of the concerned field are also available. With the availability of internet in remote areas MOOCs has made it possible for many people to avail the benefits of higher education without attending regular classes or not being able to earn simultaneously. Course material is lucid as well as comprehensive and students can easily avail its benefits with just access to internet.</p>

	<p style="line-height:2">All the necessary updates and developments in the MOOCs world are ingested here .This magazine is a ready guide for all the updates and developments in the world of MOOCs. Students opting for our different courses can access our website for daily updates and changes. This website has been developed with a view to facilitate our associated students with a knowledge sharing forum. </p>

{% endblock %}

templates/base.html
{%load staticfiles %}
<!DOCTYPE html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<title>
			{% block title %}MOOCS Magazine{% endblock %}
		</title>
		<link rel='stylesheet' href='/static/css/font-awesome.css' type="text/css">
		<link rel='stylesheet' href='/static/css/bootstrap-responsive.css' type="text/css">
		<link rel='stylesheet' href='/static/css/style.min.css' type="text/css">
		<link rel='stylesheet' href='/static/css/stylesheet.css' type="text/css">
		<link rel='stylesheet' href='/static/css/bootstrap.css' type="text/css">
		<link rel='stylesheet' href='/static/css/jquery.mCustomScrollbar.css' type="text/css">
		<script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
		
		
		<script src="{% static 'js/jquery.easing.1.3.js' %}"></script>
		<script src="{% static 'js/jslib.js' %}"></script>
    	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"> </script>
    	
    	
    </head>
    
    
	<body>
		<div class="all_container">
			{% block page_header %}
			<!-- Header Begins -->
				<div id="header">
					<div id="content">
						<div class="header_main">
							<div class="span4 logo">
								<a href="/" title="MOOCS Magazine"><img src="/static/images/logo.png" alt="MOOCS Magazine"></a>
							</div>
							
							<div class="span8 header-right">
								<a href="/blog/">
									<div class="top_box color_orange">
									<img src="/static/images/blog_icon.png">
									<span>Blog</span>
									</div>
								</a>
									<a href="/news/">
								<div class="top_box color_green">
									<img src="/static/images/news_icon.png">
									<span>News</span>
								</div>
								</a>
								
							</div>
						</div>
					</div>
				</div>
			<!-- Header Ends -->
			{% endblock %}

			{% block navigation %}
			<!-- Navigation Begin -->
			<div class="clear"></div>
			<nav>
				<div id="navigation">
					<div id="content">
						<ul>
							<li {% if page == '/' %}class="active"{% endif %}>
								<a href="{% url 'homepage' %}">
								<span class="fa fa-home"></span>
								home</a>
							</li>
							<li {% if page == '/about/' %}class="active"{% endif %}>

								<a href="{% url 'about' %}">About Us</a>
							</li>
							<li {% if page == '/contact/' %}class="active"{% endif %}>
								<a href="{% url 'contact' %}">Contact Us</a>
							</li>
						</ul>

						<form action="/search/" method="get" id="search" name="contact-form">{% csrf_token %}
							<input placeholder="Enter your search term..." type="text" id="id_q" name="q" class="field" style="display:inline;" required=true>

							<input type="submit" value="Search" id="searchsubmit">


						
							<div class="clear"></div>
						</form>
						
			
			
			<div class="login-txt" id="login">
			    {% if UP %}
					    	Welcome, {{UP.display_name}} <a href="/logout"> &nbsp;&nbsp;&nbsp;Logout</a>
				{%else%}
				<a ><p>Login </p> / <span><a href="/signup/"> Sign up</span></a>
				
				<div id="login-form">
					<form name="login-form" action="#" class="login-form" method="post">
						<div class="content">
							<a href="#">facebook</a><a herf="#">twitter</a>
							<input  type="text" class="input username" placeholder="Email" id="login_email"/>
				
			                <div class="user-icon"></div>
			
			                <input type="password" class="input password" placeholder="Password" id="login_pwd"/>
			
			                <div class="pass-icon"></div>                     
							
							<div id="login_error_div">
							
							</div>
							
							<br class="clear">
				        </div>
				        
				        <div class="footer">
				        	<input type="button"  value="Login" class="button" onclick="validate(document.getElementById('login_email').value,document.getElementById('login_pwd').value);"/>
				
				            <p class="forpass"> <a >Forget Password</a></p>
				       </div>
				       
				    </form>
			  </div>
				
				              
				
			               <div id="forget-form" >
								<form name="forget-form"   class="login-form" action="#">
									<div class="content">
									<br/>      
									<input  type="text" class="input email" id="forget_email" placeholder="Enter Your Email Id" />
			                
			               
			
						              <div id="forget_error_div">
										
									  </div>
						  
						  			<br class="clear">
			
			              		</div>
						
								<div class="footer">
					
					                <input type="button"  value="Submit" class="button noEnterSubmit" id="forget_button_id"  onclick="forgetPWD(document.getElementById('forget_email').value);"/>
					
					            </div>
					
			            		</form>
						</div>
			
			 
			{%endif%}
		</div>

		<br class="clear">
					</div>
				</div>
			</nav>		
			<!-- Navigation Ends -->
			{% endblock %}

			{% block slider %}
			{% endblock %}

			{% block main %}
			{% endblock %}

			{% block footer %}
			<div class="clear"></div>
			<footer>
				<div id="footer">
					<div id="content">
						<div class="copyrights">
							© 2014 MOOCS Magazine All rights reserved
						</div>
						<div class="social_footer">
							<ul>
								<li class="facebook">
									<a title="" href="https://www.facebook.com/BrentwoodsEducation">Facebook</a>
								</li>
								<li class="twitter">
									<a title="" href="">Twitter</a>
								</li>

							</ul>
						</div><br class="clear">
					</div>
				</div>
			</footer>
			{% endblock %}
		</div>
		<script type='text/javascript' src='/static/js/bootstrap.min.js'></script>
		<script type='text/javascript' src='/static/js/jquery.mCustomScrollbar.js'></script>
		<script type='text/javascript' src='/static/js/jquery.fitvids.js'></script>
		<script type='text/javascript' src='/static/js/jquery-ui.js'></script>
		<script type='text/javascript' src='/static/js/magnific-popup.js'></script>
		<script type='text/javascript' src='/static/js/jquery.bxslider.min.js'></script>
		<script type='text/javascript' src='/static/js/base.js'></script>
		<script type="text/javascript">
			var $j=jQuery.noConflict();$j(function(){var b=0;var a=$j(".bxslider_2").show().bxSlider({pagerCustom:".bxslider-pager, .featured_vids",auto:true,speed:500,pause:5000,autoHover:true,easing:"easeOutCirc",useCSS:false,onSliderLoad:function(){$j(".featured_item").removeClass("current_slide");$j('.featured_item h3 a[data-slide-index="'+b+'"]').parents(".featured_item").addClass("current_slide");$j(".featured_vids").mCustomScrollbar("scrollTo",'.featured_item[data-slide-index="'+b+'"]')},onSlideAfter:function(){var c=a.getCurrentSlide();$j(".featured_item").removeClass("current_slide");$j('.featured_item h3 a[data-slide-index="'+c+'"]').parents(".featured_item").addClass("current_slide");$j(".featured_vids").mCustomScrollbar("scrollTo",'.featured_item[data-slide-index="'+c+'"]')},});$j("#bxslider_next").click(function(){a.goToNextSlide();return false});$j("#bxslider_prev").click(function(){a.goToPrevSlide();return false})});$j(function(){$j(".featured_vids").mCustomScrollbar({theme:"light-thick"})});
		</script>
	</body>
</html>

templates/base_with_structure.html
{% extends 'base.html' %}
{%load popular%}
{% load staticfiles %}
{% load imagefit %}

{% load blog_tags %}

{% block main %}
<div id="content" class="margin-top40">
	<div class="content_container">

			{% block content %}
			{% endblock %}

	</div>

	{% block sidebar %}
		<div class="sidebar_big" style="margin-left:25px">
		<div id="tabbedwidget-3" class="widget-area ui-tabs ui-widget ui-widget-content ui-corner-all">

			<script type='text/javascript' src='/static/js/jquery-1.8.2.min.js'>
			</script>
			<script type="text/javascript">var $j=jQuery.noConflict();$j(function(){$j("#tabbedwidget-3").tabs()});
			</script>

			<div class="tabbed_widget cat_style_6">
				<ul class="tabs_ul" style="margin-bottom:30px">
					<li>
						<a href="#popular_posts_01">Popular</a>
					</li>
					<li>
						<a href="#posts_comments02">Comments</a>
					</li>
						<div class="clear"></div>
				</ul>
			</div>
			<div class="cat_style_3" id="popular_posts_01">
			
			<!-- Popular Post begins -->
				{% popularposts %}
			<!-- Popular post ends -->

			</div>
			


			<!-- Recent comments begins -->
			<div class="cat_style_3" id="posts_comments02">
			{% block recent_comments %}
			{% get_latest_content blog.Comment 4 as recent_comments %}
				{% for comment in recent_comments %}
					<div class="cat_style_item cat_style_3_item comment_style_item">
						<div class="cat_style_image">
							<div class="cat_style_photo">

								
								<a href="#">



									<img src= 
								{% if comment.user.profile.image %}
            "{% static comment.user.profile.image|resize:"65x65,C" %}"
        {% else %}
        "/static/images/comments.png"
        {% endif %}
									 alt="Comment" title="{{comment.user.username}}" />
								</a>
							</div>
						</div>
						<div class="speacer"></div>
						<div class="cat_style_info">
							<h3>
								<a href="{{comment.post.get_absolute_url}}">{{comment.body|truncatewords_html:"4"|safe}}</a>
							</h3>
							<div class="meta-info">
								<span class="fa fa-clock-o"></span>&nbsp;&nbsp;On {{comment.pub_date|date:"F j, Y"}}
							</div>
						</div>
						<div class="clear"></div>
					</div>
				{% endfor %}
			{% endblock %}
			</div>
			<!-- Recent Comments ends -->

		</div>


		{% block newletter %}

		<div class="join_newsletter" >
			<div class="nice_heading" >
				<h3>
					Join our Newsletter
				</h3>
			</div>

			<form action="/subscribe" enctype="multipart/form-data" method="post" id="join_newsletter" name="contact-form">
			{% csrf_token %}
				<p>
					Subscribe to our free weekly newsletter for news and new courses
				</p>
				<div style="height:80px">
					
				<p class="errormsg" style="color:red;"></p>
				<input placeholder="Enter your email address" type="text" id="id_email_field" name="email_field" class="field"> 
				
				</div>
				<input type="submit" value="Subscribe" class="submit-button" name="" id="submit-button"
				>
			
				<div class="clear"></div>
			</form>
		</div>

		{% endblock%}


		{% block archive %}
		<div class="archive">
			<div class="nice_heading">
				<h3>
					Archive
				</h3>
			</div>
			<ul>
				{% for month in months %}
				<li>
					<a href="/blog/{{month.1}}/{{month.0|lower|slice:"3"}}">{{month.0}} - {{month.1}}</a>
				</li>
				{% endfor %}
			</ul>
		</div>
		{% endblock %}


		{% block video %}
		<!--	<div class="video">
			<div class="nice_heading">
			<h3>Video Box</h3>
			</div>
			<div>

				<iframe width="300" height="170" src="//www.youtube.com/embed/DpN5ko0C2y8" frameborder="0" allowfullscreen></iframe>

			</div>
		</div> -->
		{% endblock %}

		{% block popular_tags %}
		<div class="popular_tags">
			<div class="nice_heading">
				<h3>
					Popular Tags
				</h3>
			</div>
			<div class="tagcloud">
                 {%populartags%}
			</div>
		</div>
		{% endblock %}
	</div>
	{% endblock %}
	
</div>
{% endblock %}